// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct TradevaultArenaClientProgram;
impl sails_rs::client::Program for TradevaultArenaClientProgram {}
pub trait TradevaultArenaClient {
    type Env: sails_rs::client::GearEnv;
    fn tradevault_arena(
        &self,
    ) -> sails_rs::client::Service<tradevault_arena::TradevaultArenaImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> TradevaultArenaClient
    for sails_rs::client::Actor<TradevaultArenaClientProgram, E>
{
    type Env = E;
    fn tradevault_arena(
        &self,
    ) -> sails_rs::client::Service<tradevault_arena::TradevaultArenaImpl, Self::Env> {
        self.service(stringify!(TradevaultArena))
    }
}
pub trait TradevaultArenaClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        initial_btc_price: u128,
    ) -> sails_rs::client::PendingCtor<TradevaultArenaClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> TradevaultArenaClientCtors
    for sails_rs::client::Deployment<TradevaultArenaClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        initial_btc_price: u128,
    ) -> sails_rs::client::PendingCtor<TradevaultArenaClientProgram, io::Create, Self::Env> {
        self.pending_ctor((initial_btc_price,))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (initial_btc_price: u128) -> ());
}

pub mod tradevault_arena {
    use super::*;
    pub trait TradevaultArena {
        type Env: sails_rs::client::GearEnv;
        fn add_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddKeeper, Self::Env>;
        fn claim_reward(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimReward, Self::Env>;
        fn close_position(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env>;
        fn create_tournament(
            &mut self,
            name: String,
            entry_fee: u128,
            start_time: u64,
            end_time: u64,
            initial_virtual_balance: u128,
            max_participants: u32,
        ) -> sails_rs::client::PendingCall<io::CreateTournament, Self::Env>;
        fn end_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::EndTournament, Self::Env>;
        fn join_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::JoinTournament, Self::Env>;
        fn keeper_tick(
            &mut self,
            tournament_id: u64,
            new_btc_price: u128,
        ) -> sails_rs::client::PendingCall<io::KeeperTick, Self::Env>;
        fn open_position(
            &mut self,
            tournament_id: u64,
            direction: PositionDirection,
            size: u128,
            stop_loss_price: Option<u128>,
            take_profit_price: Option<u128>,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env>;
        fn process_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ProcessTournament, Self::Env>;
        fn remove_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveKeeper, Self::Env>;
        fn settle_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleTournament, Self::Env>;
        fn update_mock_price(
            &mut self,
            new_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdateMockPrice, Self::Env>;
        fn update_price_and_process(
            &mut self,
            tournament_id: u64,
            new_btc_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePriceAndProcess, Self::Env>;
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env>;
        fn current_mock_price(
            &self,
        ) -> sails_rs::client::PendingCall<io::CurrentMockPrice, Self::Env>;
        fn is_keeper(
            &self,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsKeeper, Self::Env>;
        fn keepers(&self) -> sails_rs::client::PendingCall<io::Keepers, Self::Env>;
        fn last_price_update_time(
            &self,
        ) -> sails_rs::client::PendingCall<io::LastPriceUpdateTime, Self::Env>;
        fn leaderboard(
            &self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env>;
        fn max_stale_ms(&self) -> sails_rs::client::PendingCall<io::MaxStaleMs, Self::Env>;
        fn participant(
            &self,
            tournament_id: u64,
            participant: ActorId,
        ) -> sails_rs::client::PendingCall<io::Participant, Self::Env>;
        fn tournament(
            &self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::Tournament, Self::Env>;
        fn tournaments(&self) -> sails_rs::client::PendingCall<io::Tournaments, Self::Env>;
    }
    pub struct TradevaultArenaImpl;
    impl<E: sails_rs::client::GearEnv> TradevaultArena
        for sails_rs::client::Service<TradevaultArenaImpl, E>
    {
        type Env = E;
        fn add_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::AddKeeper, Self::Env> {
            self.pending_call((keeper,))
        }
        fn claim_reward(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimReward, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn close_position(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClosePosition, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn create_tournament(
            &mut self,
            name: String,
            entry_fee: u128,
            start_time: u64,
            end_time: u64,
            initial_virtual_balance: u128,
            max_participants: u32,
        ) -> sails_rs::client::PendingCall<io::CreateTournament, Self::Env> {
            self.pending_call((
                name,
                entry_fee,
                start_time,
                end_time,
                initial_virtual_balance,
                max_participants,
            ))
        }
        fn end_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::EndTournament, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn join_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::JoinTournament, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn keeper_tick(
            &mut self,
            tournament_id: u64,
            new_btc_price: u128,
        ) -> sails_rs::client::PendingCall<io::KeeperTick, Self::Env> {
            self.pending_call((tournament_id, new_btc_price))
        }
        fn open_position(
            &mut self,
            tournament_id: u64,
            direction: PositionDirection,
            size: u128,
            stop_loss_price: Option<u128>,
            take_profit_price: Option<u128>,
        ) -> sails_rs::client::PendingCall<io::OpenPosition, Self::Env> {
            self.pending_call((
                tournament_id,
                direction,
                size,
                stop_loss_price,
                take_profit_price,
            ))
        }
        fn process_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::ProcessTournament, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn remove_keeper(
            &mut self,
            keeper: ActorId,
        ) -> sails_rs::client::PendingCall<io::RemoveKeeper, Self::Env> {
            self.pending_call((keeper,))
        }
        fn settle_tournament(
            &mut self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::SettleTournament, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn update_mock_price(
            &mut self,
            new_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdateMockPrice, Self::Env> {
            self.pending_call((new_price,))
        }
        fn update_price_and_process(
            &mut self,
            tournament_id: u64,
            new_btc_price: u128,
        ) -> sails_rs::client::PendingCall<io::UpdatePriceAndProcess, Self::Env> {
            self.pending_call((tournament_id, new_btc_price))
        }
        fn admin(&self) -> sails_rs::client::PendingCall<io::Admin, Self::Env> {
            self.pending_call(())
        }
        fn current_mock_price(
            &self,
        ) -> sails_rs::client::PendingCall<io::CurrentMockPrice, Self::Env> {
            self.pending_call(())
        }
        fn is_keeper(
            &self,
            address: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsKeeper, Self::Env> {
            self.pending_call((address,))
        }
        fn keepers(&self) -> sails_rs::client::PendingCall<io::Keepers, Self::Env> {
            self.pending_call(())
        }
        fn last_price_update_time(
            &self,
        ) -> sails_rs::client::PendingCall<io::LastPriceUpdateTime, Self::Env> {
            self.pending_call(())
        }
        fn leaderboard(
            &self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::Leaderboard, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn max_stale_ms(&self) -> sails_rs::client::PendingCall<io::MaxStaleMs, Self::Env> {
            self.pending_call(())
        }
        fn participant(
            &self,
            tournament_id: u64,
            participant: ActorId,
        ) -> sails_rs::client::PendingCall<io::Participant, Self::Env> {
            self.pending_call((tournament_id, participant))
        }
        fn tournament(
            &self,
            tournament_id: u64,
        ) -> sails_rs::client::PendingCall<io::Tournament, Self::Env> {
            self.pending_call((tournament_id,))
        }
        fn tournaments(&self) -> sails_rs::client::PendingCall<io::Tournaments, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddKeeper (keeper: ActorId) -> bool);
        sails_rs::io_struct_impl!(ClaimReward (tournament_id: u64) -> u128);
        sails_rs::io_struct_impl!(ClosePosition (tournament_id: u64) -> super::ParticipantView);
        sails_rs::io_struct_impl!(CreateTournament (name: String, entry_fee: u128, start_time: u64, end_time: u64, initial_virtual_balance: u128, max_participants: u32) -> super::TournamentView);
        sails_rs::io_struct_impl!(EndTournament (tournament_id: u64) -> super::TournamentView);
        sails_rs::io_struct_impl!(JoinTournament (tournament_id: u64) -> super::ParticipantView);
        sails_rs::io_struct_impl!(KeeperTick (tournament_id: u64, new_btc_price: u128) -> super::KeeperTickSummary);
        sails_rs::io_struct_impl!(OpenPosition (tournament_id: u64, direction: super::PositionDirection, size: u128, stop_loss_price: Option<u128>, take_profit_price: Option<u128>) -> super::ParticipantView);
        sails_rs::io_struct_impl!(ProcessTournament (tournament_id: u64) -> super::KeeperTickSummary);
        sails_rs::io_struct_impl!(RemoveKeeper (keeper: ActorId) -> bool);
        sails_rs::io_struct_impl!(SettleTournament (tournament_id: u64) -> super::SettlementResult);
        sails_rs::io_struct_impl!(UpdateMockPrice (new_price: u128) -> u128);
        sails_rs::io_struct_impl!(UpdatePriceAndProcess (tournament_id: u64, new_btc_price: u128) -> super::KeeperTickSummary);
        sails_rs::io_struct_impl!(Admin () -> ActorId);
        sails_rs::io_struct_impl!(CurrentMockPrice () -> u128);
        sails_rs::io_struct_impl!(IsKeeper (address: ActorId) -> bool);
        sails_rs::io_struct_impl!(Keepers () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(LastPriceUpdateTime () -> u64);
        sails_rs::io_struct_impl!(Leaderboard (tournament_id: u64) -> Vec<super::LeaderboardEntry>);
        sails_rs::io_struct_impl!(MaxStaleMs () -> u64);
        sails_rs::io_struct_impl!(Participant (tournament_id: u64, participant: ActorId) -> super::ParticipantView);
        sails_rs::io_struct_impl!(Tournament (tournament_id: u64) -> super::TournamentView);
        sails_rs::io_struct_impl!(Tournaments () -> Vec<super::TournamentView>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum TradevaultArenaEvents {
            TournamentCreated {
                tournament_id: u64,
                name: String,
            },
            TournamentJoined {
                tournament_id: u64,
                participant: ActorId,
                prize_pool: u128,
            },
            MockPriceUpdated {
                price: u128,
            },
            PriceUpdated {
                tournament_id: u64,
                price: u128,
                timestamp: u64,
            },
            KeeperAdded {
                keeper: ActorId,
            },
            KeeperRemoved {
                keeper: ActorId,
            },
            PositionOpened {
                tournament_id: u64,
                participant: ActorId,
                direction: PositionDirection,
                size: u128,
                entry_price: u128,
                stop_loss_price: Option<u128>,
                take_profit_price: Option<u128>,
            },
            PositionClosed {
                tournament_id: u64,
                participant: ActorId,
                realized_pnl: i128,
                exit_price: u128,
                close_reason: CloseReason,
            },
            StopLossTriggered {
                tournament_id: u64,
                participant: ActorId,
                trigger_price: u128,
            },
            TakeProfitTriggered {
                tournament_id: u64,
                participant: ActorId,
                trigger_price: u128,
            },
            TournamentEnded {
                tournament_id: u64,
                final_btc_price: u128,
            },
            TournamentSettled {
                tournament_id: u64,
                winners: Vec<WinnerPayout>,
            },
            KeeperTickProcessed {
                tournament_id: u64,
                positions_closed: u32,
                tournament_ended: bool,
                tournament_settled: bool,
            },
            RewardClaimed {
                tournament_id: u64,
                participant: ActorId,
                payout: u128,
            },
        }
        impl sails_rs::client::Event for TradevaultArenaEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "TournamentCreated",
                "TournamentJoined",
                "MockPriceUpdated",
                "PriceUpdated",
                "KeeperAdded",
                "KeeperRemoved",
                "PositionOpened",
                "PositionClosed",
                "StopLossTriggered",
                "TakeProfitTriggered",
                "TournamentEnded",
                "TournamentSettled",
                "KeeperTickProcessed",
                "RewardClaimed",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for TradevaultArenaImpl {
            type Event = TradevaultArenaEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct ParticipantView {
    pub tournament_id: u64,
    pub participant: ActorId,
    pub initial_virtual_balance: u128,
    pub realized_pnl: i128,
    pub unrealized_pnl: i128,
    pub final_value: i128,
    pub return_percentage_bps: i128,
    pub position: Option<Position>,
    pub claimable_reward: u128,
    pub last_close_reason: Option<CloseReason>,
    pub last_close_price: Option<u128>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Position {
    pub entry_price: u128,
    pub size: u128,
    pub direction: PositionDirection,
    pub stop_loss_price: Option<u128>,
    pub take_profit_price: Option<u128>,
    pub is_open: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum PositionDirection {
    Long,
    Short,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum CloseReason {
    Manual,
    StopLoss,
    TakeProfit,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TournamentView {
    pub tournament_id: u64,
    pub name: String,
    pub entry_fee: u128,
    pub start_time: u64,
    pub end_time: u64,
    pub initial_virtual_balance: u128,
    pub max_participants: u32,
    pub participant_count: u32,
    pub prize_pool: u128,
    pub status: TournamentStatus,
    pub final_btc_price: Option<u128>,
    pub winners: Vec<WinnerPayout>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum TournamentStatus {
    Upcoming,
    Active,
    Ended,
    Settled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct WinnerPayout {
    pub rank: u8,
    pub participant: ActorId,
    pub payout: u128,
    pub final_value: i128,
    pub return_percentage_bps: i128,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct KeeperTickSummary {
    pub price_updated: bool,
    pub positions_closed: u32,
    pub tournament_ended: bool,
    pub tournament_settled: bool,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct SettlementResult {
    pub tournament_id: u64,
    pub final_btc_price: u128,
    pub prize_pool: u128,
    pub winners: Vec<WinnerPayout>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct LeaderboardEntry {
    pub rank: u8,
    pub participant: ActorId,
    pub final_value: i128,
    pub realized_pnl: i128,
    pub unrealized_pnl: i128,
    pub return_percentage_bps: i128,
    pub position: Option<Position>,
}
